### ISSUE TITLE
Backslash in strings brokes highlight

### ISSUE THREAD

**Issue by yauhenko** [zephir-lang/idea-plugin#12]
Syntax highlight brokes at my preg mask.
`let sql = preg_replace("/\?/", this->val(value), sql, 1);`
 
![Screenshot from IDE](https://i.imgur.com/CoGxya5.png "Backslash in strings brokes highlight")

**Comment by sergeyklay** [comment]
@AsterAI Could you please take a look

**Comment by AsterAI** [comment]
Hi, hm... I try fix it.

**Comment by yauhenko** [comment]
Any news?

**Comment by sergeyklay** [comment]
@yauhenko AFAIK it is fixed now. Is still issue relevant for you? What plugin version do you use?

**Comment by yauhenko** [comment]
> @yauhenko AFAIK it is fixed now. Is still issue relevant for you? What plugin version do you use?

Yes, issue is still relevant for me.
Plugin version: **0.3.3**

IDE: PhpStorm 2019.3
Build #PS-193.5233.101, built on November 28, 2019

**Comment by sergeyklay** [comment]
I'm sorry. Was too busy these days. I'll take a look as soon as possible.

**Comment by sergeyklay** [comment]
As far as I see this issue has bin solved. 

**InelliJ**
![image](https://user-images.githubusercontent.com/1256298/87048287-369ae500-c204-11ea-9488-98471af826d6.png)


**PhpStorm**
![image](https://user-images.githubusercontent.com/1256298/87048390-53cfb380-c204-11ea-8730-1df3141b8668.png)
